version: '3.1'

services:
  # MONGODB
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017

  # MONGO-EXPRESS
  mongo-dashboard:
    depends_on:
      - mongo
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/

  # REDIS DB
  redis:
    image: redis

  # BEACHU WEBSERVICE
  webservice:
    image: lucapanariello/beachu
    env_file: .env
    environment:
      NODE_ENV: production
      REDIS_URL: redis://redis
    ports:
      - 3000:3000
    restart: always
    deploy:
      mode: replicated
      replicas: 3
